Implemented Canvas Downloading
aabounegm/vue-pixel-board pull request #24
Opened 2021-01-04 02:20 UTC by Elgayar

2021-01-04 02:30 UTC, Elgayar commented
Works for me on Chrome (87.0.4280.88), Edge (87.0.664.66), and Firefox (80.0.1).
Does not work on IE11

2021-01-05 11:26 UTC, aabounegm requested changes
I don't like the extra lines between the methods 😅
But great work overall

2021-01-05 11:26 UTC, aabounegm commented on src/components/Board.vue
> +    		downloadLink.setAttribute('download', 'canvas.png');
Mix of tabs and spaces

2021-01-05 11:26 UTC, aabounegm commented on src/components/Board.vue
> +		    let downloadLink = document.createElement('a');
You can still use `const` here as the variable is not being reassigned

2021-01-05 11:26 UTC, aabounegm commented on src/components/Board.vue
> +			const url = this.ctx.canvas.toDataURL('image/png').replace(/^data:image\/[^;]/, 'data:application/octet-stream');
```suggestion
		saveBoard(mimeType = 'image/png') {
			const url = this.ctx.canvas.toDataURL(mimeType).replace(/^data:image\/[^;]/, 'data:application/octet-stream');
```
To allow changing to `jpeg` or something

2021-01-05 11:26 UTC, aabounegm commented on src/components/Board.vue
> +		saveBoard() {
I think `downloadImage` is a more appropriate name

2021-01-06 15:07 UTC, aabounegm approved these changes

2021-01-10 02:10 UTC, merged